### ISSUE TITLE
How do I play the game?

### ISSUE THREAD

**Issue by UBUNTUTHEDISTRO** [CloneTrooper1019/Roblox_0.3.368.0#45]
Not an issue, but I have never seen old Roblox Studio before.

**Comment by UBUNTUTHEDISTRO** [comment]
Okay, I have found a way. It is very hard, but listen.
1. Load a game. Simple.
2. Go to View > Toolbars > Command
3. Enter the commands below in the right order
4. game.Players:createLocalPlayer(0)
5. game.Players.LocalPlayer:LoadCharacter()
6. Press the run button
7. Un-check Edit Mode
And there you go! Hope this helped.

**Comment by UBUNTUTHEDISTRO** [comment]
Also, I haven't figured out a way to respawn. Maybe sometime later.

**Comment by burstpup** [comment]
Follow your own instructions up to Step 3. Then, instead of the fourth step, use this script instead. It *should* respawn you, but I haven't tested. Wrote this in under a minute.

local player = game.Players:CreateLocalPlayer(0) player.CharacterAdded:Connect(function(character) local humanoid = character:WaitForChild("Humanoid") humanoid.Died:Connect(function() wait(5) player:LoadCharacter() end) end) player:LoadCharacter()
